"""Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT."""

from __future__ import annotations
import dataclasses
from typing import Optional



@dataclasses.dataclass
class BodyLoginAPIV1TokenPost:
    password: str = dataclasses.field(metadata={'form': { 'field_name': 'password' }})
    username: str = dataclasses.field(metadata={'form': { 'field_name': 'username' }})
    client_id: Optional[str] = dataclasses.field(default=None, metadata={'form': { 'field_name': 'client_id' }})
    client_secret: Optional[str] = dataclasses.field(default=None, metadata={'form': { 'field_name': 'client_secret' }})
    grant_type: Optional[str] = dataclasses.field(default=None, metadata={'form': { 'field_name': 'grant_type' }})
    scope: Optional[str] = dataclasses.field(default=None, metadata={'form': { 'field_name': 'scope' }})
    

