"""Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT."""

from __future__ import annotations
import dataclasses
from dataclasses_json import Undefined, dataclass_json
from lk import utils


@dataclass_json(undefined=Undefined.EXCLUDE)
@dataclasses.dataclass
class Customer:
    r"""Represents info about order customer"""
    
    email: str = dataclasses.field(metadata={'dataclasses_json': { 'letter_case': utils.get_field_name('email') }})
    erp_id: int = dataclasses.field(metadata={'dataclasses_json': { 'letter_case': utils.get_field_name('erp_id') }})
    r"""This field could be numeric string"""
    first_name: str = dataclasses.field(metadata={'dataclasses_json': { 'letter_case': utils.get_field_name('first_name') }})
    human_id: int = dataclasses.field(metadata={'dataclasses_json': { 'letter_case': utils.get_field_name('human_id') }})
    r"""This field could be numeric string"""
    id: int = dataclasses.field(metadata={'dataclasses_json': { 'letter_case': utils.get_field_name('id') }})
    r"""This field could be numeric string"""
    last_name: str = dataclasses.field(metadata={'dataclasses_json': { 'letter_case': utils.get_field_name('last_name') }})
    middle_name: str = dataclasses.field(metadata={'dataclasses_json': { 'letter_case': utils.get_field_name('middle_name') }})
    phone: str = dataclasses.field(metadata={'dataclasses_json': { 'letter_case': utils.get_field_name('phone') }})
    