"""Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT."""

from __future__ import annotations
from enum import Enum

class PaymentMethod(int, Enum):
    r"""An enumeration."""
    ZERO = 0
    ONE = 1
